#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

#echo Running migrations...
#alembic upgrade head

echo Starting Litestar App...
uvicorn app.main:app --host "${APP_HOST:-0.0.0.0}" \
                     --port "${APP_PORT:-8000}"